#%RAML 1.0
title: MuleSoft Accounts

types:
  Account: !include /AccountDataType.raml

/accounts:
  get:
    queryParameters:
      requestor:
      type:
        required: false
        enum:
          - personal
          - business
      name:
        required: false
    responses:
      200:
        body:
          application/json:
            type: Account
            examples:
              output: !include /examples/AccountExample.raml
  post:
    body:
      application/json:
        type: Account[]
        examples:
          input: !include /examples/AccountExamples.raml
    responses:
      201:
        body:
          application/json:
            example:
              message: Accounts created
